### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: inference_graph_50000_balance\frozen_inference_graph.pb: The system cannot find the path specified; No such process 

### ISSUE THREAD

**Issue by angelgaspar** [mohammadakz/Nested_PPE_detection#2]
Hi, I'm trying to run your project however I get the error mentioned above. Do you have the file or how can I create it?

Thanks!

**Comment by mohammadakz** [comment]
@angelgaspar Hi, 
The error you are facing is because the "frozen_inference_graph.pb" file is not there.
You need to replace it with you own trained model
